# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        app.in_memory:
            memory:
                users:
                    user:
                        password:           user
                        roles:              ROLE_USER
                    admin:
                        password:           admin
                        roles:              [ROLE_USER, ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            http_basic:
                provider: app.in_memory

    access_control:
        - { path: ^/orders, roles: [IS_AUTHENTICATED_FULLY ]}
