# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    customer.filters.search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments:
            -
                uuid: 'exact'
                name: 'partial'
        tags:      [ { name: 'api_platform.filter', id: 'customer.search' } ]


    order.filters.search:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments:
            -
                customer.uuid: 'exact'
                username: 'exact'

        tags:      [ { name: 'api_platform.filter', id: 'order.search' } ]

    app.serializer.admin_context_builder:
        decorates: api_platform.serializer.context_builder
        class: AppBundle\Serializer\AdminContextBuilder
        arguments: ['@app.serializer.admin_context_builder.inner', '@security.authorization_checker']
